// flow-typed signature: 590703f8d89ec068cf0e7a0e1d7a8115
// flow-typed version: <<STUB>>/moxios_v^0.3.0/flow_v0.34.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'moxios'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'moxios' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'moxios/dist/moxios' {
  declare module.exports: any;
}

declare module 'moxios/dist/moxios.min' {
  declare module.exports: any;
}

// Filename aliases
declare module 'moxios/dist/moxios.js' {
  declare module.exports: $Exports<'moxios/dist/moxios'>;
}
declare module 'moxios/dist/moxios.min.js' {
  declare module.exports: $Exports<'moxios/dist/moxios.min'>;
}
