// flow-typed signature: 02779314605ef7a2f9a076e16177482f
// flow-typed version: <<STUB>>/react-popup_v^0.4.2/flow_v0.34.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-popup'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-popup' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-popup/dist/ActionButton.react' {
  declare module.exports: any;
}

declare module 'react-popup/dist/Footer.react' {
  declare module.exports: any;
}

declare module 'react-popup/dist/Header.react' {
  declare module.exports: any;
}

declare module 'react-popup/dist/index' {
  declare module.exports: any;
}

declare module 'react-popup/dist/Input.react' {
  declare module.exports: any;
}

declare module 'react-popup/gulpfile' {
  declare module.exports: any;
}

declare module 'react-popup/src/ActionButton.react' {
  declare module.exports: any;
}

declare module 'react-popup/src/Footer.react' {
  declare module.exports: any;
}

declare module 'react-popup/src/Header.react' {
  declare module.exports: any;
}

declare module 'react-popup/src/index' {
  declare module.exports: any;
}

declare module 'react-popup/src/Input.react' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-popup/dist/ActionButton.react.js' {
  declare module.exports: $Exports<'react-popup/dist/ActionButton.react'>;
}
declare module 'react-popup/dist/Footer.react.js' {
  declare module.exports: $Exports<'react-popup/dist/Footer.react'>;
}
declare module 'react-popup/dist/Header.react.js' {
  declare module.exports: $Exports<'react-popup/dist/Header.react'>;
}
declare module 'react-popup/dist/index.js' {
  declare module.exports: $Exports<'react-popup/dist/index'>;
}
declare module 'react-popup/dist/Input.react.js' {
  declare module.exports: $Exports<'react-popup/dist/Input.react'>;
}
declare module 'react-popup/gulpfile.js' {
  declare module.exports: $Exports<'react-popup/gulpfile'>;
}
declare module 'react-popup/src/ActionButton.react.js' {
  declare module.exports: $Exports<'react-popup/src/ActionButton.react'>;
}
declare module 'react-popup/src/Footer.react.js' {
  declare module.exports: $Exports<'react-popup/src/Footer.react'>;
}
declare module 'react-popup/src/Header.react.js' {
  declare module.exports: $Exports<'react-popup/src/Header.react'>;
}
declare module 'react-popup/src/index.js' {
  declare module.exports: $Exports<'react-popup/src/index'>;
}
declare module 'react-popup/src/Input.react.js' {
  declare module.exports: $Exports<'react-popup/src/Input.react'>;
}
