// flow-typed signature: 3919133c19e969306cab9b81caebdde3
// flow-typed version: <<STUB>>/react-bootstrap-table_v^2.5.2/flow_v0.34.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-bootstrap-table'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-bootstrap-table' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-bootstrap-table/dist/react-bootstrap-table' {
  declare module.exports: any;
}

declare module 'react-bootstrap-table/dist/react-bootstrap-table.min' {
  declare module.exports: any;
}

declare module 'react-bootstrap-table/lib/BootstrapTable' {
  declare module.exports: any;
}

declare module 'react-bootstrap-table/lib/Const' {
  declare module.exports: any;
}

declare module 'react-bootstrap-table/lib/csv_export_util' {
  declare module.exports: any;
}

declare module 'react-bootstrap-table/lib/Editor' {
  declare module.exports: any;
}

declare module 'react-bootstrap-table/lib/filesaver' {
  declare module.exports: any;
}

declare module 'react-bootstrap-table/lib/Filter' {
  declare module.exports: any;
}

declare module 'react-bootstrap-table/lib/filters/Date' {
  declare module.exports: any;
}

declare module 'react-bootstrap-table/lib/filters/Number' {
  declare module.exports: any;
}

declare module 'react-bootstrap-table/lib/filters/Regex' {
  declare module.exports: any;
}

declare module 'react-bootstrap-table/lib/filters/Select' {
  declare module.exports: any;
}

declare module 'react-bootstrap-table/lib/filters/Text' {
  declare module.exports: any;
}

declare module 'react-bootstrap-table/lib/index' {
  declare module.exports: any;
}

declare module 'react-bootstrap-table/lib/Notification' {
  declare module.exports: any;
}

declare module 'react-bootstrap-table/lib/pagination/PageButton' {
  declare module.exports: any;
}

declare module 'react-bootstrap-table/lib/pagination/PaginationList' {
  declare module.exports: any;
}

declare module 'react-bootstrap-table/lib/SelectRowHeaderColumn' {
  declare module.exports: any;
}

declare module 'react-bootstrap-table/lib/store/TableDataStore' {
  declare module.exports: any;
}

declare module 'react-bootstrap-table/lib/TableBody' {
  declare module.exports: any;
}

declare module 'react-bootstrap-table/lib/TableColumn' {
  declare module.exports: any;
}

declare module 'react-bootstrap-table/lib/TableEditColumn' {
  declare module.exports: any;
}

declare module 'react-bootstrap-table/lib/TableFilter' {
  declare module.exports: any;
}

declare module 'react-bootstrap-table/lib/TableHeader' {
  declare module.exports: any;
}

declare module 'react-bootstrap-table/lib/TableHeaderColumn' {
  declare module.exports: any;
}

declare module 'react-bootstrap-table/lib/TableRow' {
  declare module.exports: any;
}

declare module 'react-bootstrap-table/lib/toolbar/ToolBar' {
  declare module.exports: any;
}

declare module 'react-bootstrap-table/lib/util' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-bootstrap-table/dist/react-bootstrap-table.js' {
  declare module.exports: $Exports<'react-bootstrap-table/dist/react-bootstrap-table'>;
}
declare module 'react-bootstrap-table/dist/react-bootstrap-table.min.js' {
  declare module.exports: $Exports<'react-bootstrap-table/dist/react-bootstrap-table.min'>;
}
declare module 'react-bootstrap-table/lib/BootstrapTable.js' {
  declare module.exports: $Exports<'react-bootstrap-table/lib/BootstrapTable'>;
}
declare module 'react-bootstrap-table/lib/Const.js' {
  declare module.exports: $Exports<'react-bootstrap-table/lib/Const'>;
}
declare module 'react-bootstrap-table/lib/csv_export_util.js' {
  declare module.exports: $Exports<'react-bootstrap-table/lib/csv_export_util'>;
}
declare module 'react-bootstrap-table/lib/Editor.js' {
  declare module.exports: $Exports<'react-bootstrap-table/lib/Editor'>;
}
declare module 'react-bootstrap-table/lib/filesaver.js' {
  declare module.exports: $Exports<'react-bootstrap-table/lib/filesaver'>;
}
declare module 'react-bootstrap-table/lib/Filter.js' {
  declare module.exports: $Exports<'react-bootstrap-table/lib/Filter'>;
}
declare module 'react-bootstrap-table/lib/filters/Date.js' {
  declare module.exports: $Exports<'react-bootstrap-table/lib/filters/Date'>;
}
declare module 'react-bootstrap-table/lib/filters/Number.js' {
  declare module.exports: $Exports<'react-bootstrap-table/lib/filters/Number'>;
}
declare module 'react-bootstrap-table/lib/filters/Regex.js' {
  declare module.exports: $Exports<'react-bootstrap-table/lib/filters/Regex'>;
}
declare module 'react-bootstrap-table/lib/filters/Select.js' {
  declare module.exports: $Exports<'react-bootstrap-table/lib/filters/Select'>;
}
declare module 'react-bootstrap-table/lib/filters/Text.js' {
  declare module.exports: $Exports<'react-bootstrap-table/lib/filters/Text'>;
}
declare module 'react-bootstrap-table/lib/index.js' {
  declare module.exports: $Exports<'react-bootstrap-table/lib/index'>;
}
declare module 'react-bootstrap-table/lib/Notification.js' {
  declare module.exports: $Exports<'react-bootstrap-table/lib/Notification'>;
}
declare module 'react-bootstrap-table/lib/pagination/PageButton.js' {
  declare module.exports: $Exports<'react-bootstrap-table/lib/pagination/PageButton'>;
}
declare module 'react-bootstrap-table/lib/pagination/PaginationList.js' {
  declare module.exports: $Exports<'react-bootstrap-table/lib/pagination/PaginationList'>;
}
declare module 'react-bootstrap-table/lib/SelectRowHeaderColumn.js' {
  declare module.exports: $Exports<'react-bootstrap-table/lib/SelectRowHeaderColumn'>;
}
declare module 'react-bootstrap-table/lib/store/TableDataStore.js' {
  declare module.exports: $Exports<'react-bootstrap-table/lib/store/TableDataStore'>;
}
declare module 'react-bootstrap-table/lib/TableBody.js' {
  declare module.exports: $Exports<'react-bootstrap-table/lib/TableBody'>;
}
declare module 'react-bootstrap-table/lib/TableColumn.js' {
  declare module.exports: $Exports<'react-bootstrap-table/lib/TableColumn'>;
}
declare module 'react-bootstrap-table/lib/TableEditColumn.js' {
  declare module.exports: $Exports<'react-bootstrap-table/lib/TableEditColumn'>;
}
declare module 'react-bootstrap-table/lib/TableFilter.js' {
  declare module.exports: $Exports<'react-bootstrap-table/lib/TableFilter'>;
}
declare module 'react-bootstrap-table/lib/TableHeader.js' {
  declare module.exports: $Exports<'react-bootstrap-table/lib/TableHeader'>;
}
declare module 'react-bootstrap-table/lib/TableHeaderColumn.js' {
  declare module.exports: $Exports<'react-bootstrap-table/lib/TableHeaderColumn'>;
}
declare module 'react-bootstrap-table/lib/TableRow.js' {
  declare module.exports: $Exports<'react-bootstrap-table/lib/TableRow'>;
}
declare module 'react-bootstrap-table/lib/toolbar/ToolBar.js' {
  declare module.exports: $Exports<'react-bootstrap-table/lib/toolbar/ToolBar'>;
}
declare module 'react-bootstrap-table/lib/util.js' {
  declare module.exports: $Exports<'react-bootstrap-table/lib/util'>;
}
