// flow-typed signature: 3604cead8a136dab4fda16de1fc3d74e
// flow-typed version: <<STUB>>/react-fontawesome_v^1.2.0/flow_v0.34.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-fontawesome'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-fontawesome' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-fontawesome/lib/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-fontawesome/lib/index.js' {
  declare module.exports: $Exports<'react-fontawesome/lib/index'>;
}
