// flow-typed signature: 8ed2fd5f7e164a503197761aad01189e
// flow-typed version: <<STUB>>/react-highcharts_v^10.0.0/flow_v0.34.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-highcharts'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-highcharts' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-highcharts/bundle/index' {
  declare module.exports: any;
}

declare module 'react-highcharts/bundle/index.src' {
  declare module.exports: any;
}

declare module 'react-highcharts/bundle/ReactHighcharts' {
  declare module.exports: any;
}

declare module 'react-highcharts/bundle/ReactHighcharts.src' {
  declare module.exports: any;
}

declare module 'react-highcharts/bundle/ReactHighmaps' {
  declare module.exports: any;
}

declare module 'react-highcharts/bundle/ReactHighmaps.src' {
  declare module.exports: any;
}

declare module 'react-highcharts/bundle/ReactHighstock' {
  declare module.exports: any;
}

declare module 'react-highcharts/bundle/ReactHighstock.src' {
  declare module.exports: any;
}

declare module 'react-highcharts/bundle/RedrawOnPrint' {
  declare module.exports: any;
}

declare module 'react-highcharts/bundle/RedrawOnPrint.src' {
  declare module.exports: any;
}

declare module 'react-highcharts/dist/bundle/index' {
  declare module.exports: any;
}

declare module 'react-highcharts/dist/bundle/index.src' {
  declare module.exports: any;
}

declare module 'react-highcharts/dist/bundle/ReactHighcharts' {
  declare module.exports: any;
}

declare module 'react-highcharts/dist/bundle/ReactHighcharts.src' {
  declare module.exports: any;
}

declare module 'react-highcharts/dist/bundle/ReactHighmaps' {
  declare module.exports: any;
}

declare module 'react-highcharts/dist/bundle/ReactHighmaps.src' {
  declare module.exports: any;
}

declare module 'react-highcharts/dist/bundle/ReactHighstock' {
  declare module.exports: any;
}

declare module 'react-highcharts/dist/bundle/ReactHighstock.src' {
  declare module.exports: any;
}

declare module 'react-highcharts/dist/bundle/RedrawOnPrint' {
  declare module.exports: any;
}

declare module 'react-highcharts/dist/bundle/RedrawOnPrint.src' {
  declare module.exports: any;
}

declare module 'react-highcharts/dist/index' {
  declare module.exports: any;
}

declare module 'react-highcharts/dist/index.src' {
  declare module.exports: any;
}

declare module 'react-highcharts/dist/ReactHighcharts' {
  declare module.exports: any;
}

declare module 'react-highcharts/dist/ReactHighcharts.src' {
  declare module.exports: any;
}

declare module 'react-highcharts/dist/ReactHighmaps' {
  declare module.exports: any;
}

declare module 'react-highcharts/dist/ReactHighmaps.src' {
  declare module.exports: any;
}

declare module 'react-highcharts/dist/ReactHighstock' {
  declare module.exports: any;
}

declare module 'react-highcharts/dist/ReactHighstock.src' {
  declare module.exports: any;
}

declare module 'react-highcharts/dist/RedrawOnPrint' {
  declare module.exports: any;
}

declare module 'react-highcharts/dist/RedrawOnPrint.src' {
  declare module.exports: any;
}

declare module 'react-highcharts/nightwatch' {
  declare module.exports: any;
}

declare module 'react-highcharts/src/bundle/ReactHighcharts' {
  declare module.exports: any;
}

declare module 'react-highcharts/src/bundle/ReactHighmaps' {
  declare module.exports: any;
}

declare module 'react-highcharts/src/bundle/ReactHighstock' {
  declare module.exports: any;
}

declare module 'react-highcharts/src/chartsFactory' {
  declare module.exports: any;
}

declare module 'react-highcharts/src/fakeHighcharts' {
  declare module.exports: any;
}

declare module 'react-highcharts/src/Highmaps' {
  declare module.exports: any;
}

declare module 'react-highcharts/src/Highstock' {
  declare module.exports: any;
}

declare module 'react-highcharts/src/More' {
  declare module.exports: any;
}

declare module 'react-highcharts/src/ReactHighcharts' {
  declare module.exports: any;
}

declare module 'react-highcharts/src/RedrawOnPrint' {
  declare module.exports: any;
}

declare module 'react-highcharts/webpack.config' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-highcharts/bundle/index.js' {
  declare module.exports: $Exports<'react-highcharts/bundle/index'>;
}
declare module 'react-highcharts/bundle/index.src.js' {
  declare module.exports: $Exports<'react-highcharts/bundle/index.src'>;
}
declare module 'react-highcharts/bundle/ReactHighcharts.js' {
  declare module.exports: $Exports<'react-highcharts/bundle/ReactHighcharts'>;
}
declare module 'react-highcharts/bundle/ReactHighcharts.src.js' {
  declare module.exports: $Exports<'react-highcharts/bundle/ReactHighcharts.src'>;
}
declare module 'react-highcharts/bundle/ReactHighmaps.js' {
  declare module.exports: $Exports<'react-highcharts/bundle/ReactHighmaps'>;
}
declare module 'react-highcharts/bundle/ReactHighmaps.src.js' {
  declare module.exports: $Exports<'react-highcharts/bundle/ReactHighmaps.src'>;
}
declare module 'react-highcharts/bundle/ReactHighstock.js' {
  declare module.exports: $Exports<'react-highcharts/bundle/ReactHighstock'>;
}
declare module 'react-highcharts/bundle/ReactHighstock.src.js' {
  declare module.exports: $Exports<'react-highcharts/bundle/ReactHighstock.src'>;
}
declare module 'react-highcharts/bundle/RedrawOnPrint.js' {
  declare module.exports: $Exports<'react-highcharts/bundle/RedrawOnPrint'>;
}
declare module 'react-highcharts/bundle/RedrawOnPrint.src.js' {
  declare module.exports: $Exports<'react-highcharts/bundle/RedrawOnPrint.src'>;
}
declare module 'react-highcharts/dist/bundle/index.js' {
  declare module.exports: $Exports<'react-highcharts/dist/bundle/index'>;
}
declare module 'react-highcharts/dist/bundle/index.src.js' {
  declare module.exports: $Exports<'react-highcharts/dist/bundle/index.src'>;
}
declare module 'react-highcharts/dist/bundle/ReactHighcharts.js' {
  declare module.exports: $Exports<'react-highcharts/dist/bundle/ReactHighcharts'>;
}
declare module 'react-highcharts/dist/bundle/ReactHighcharts.src.js' {
  declare module.exports: $Exports<'react-highcharts/dist/bundle/ReactHighcharts.src'>;
}
declare module 'react-highcharts/dist/bundle/ReactHighmaps.js' {
  declare module.exports: $Exports<'react-highcharts/dist/bundle/ReactHighmaps'>;
}
declare module 'react-highcharts/dist/bundle/ReactHighmaps.src.js' {
  declare module.exports: $Exports<'react-highcharts/dist/bundle/ReactHighmaps.src'>;
}
declare module 'react-highcharts/dist/bundle/ReactHighstock.js' {
  declare module.exports: $Exports<'react-highcharts/dist/bundle/ReactHighstock'>;
}
declare module 'react-highcharts/dist/bundle/ReactHighstock.src.js' {
  declare module.exports: $Exports<'react-highcharts/dist/bundle/ReactHighstock.src'>;
}
declare module 'react-highcharts/dist/bundle/RedrawOnPrint.js' {
  declare module.exports: $Exports<'react-highcharts/dist/bundle/RedrawOnPrint'>;
}
declare module 'react-highcharts/dist/bundle/RedrawOnPrint.src.js' {
  declare module.exports: $Exports<'react-highcharts/dist/bundle/RedrawOnPrint.src'>;
}
declare module 'react-highcharts/dist/index.js' {
  declare module.exports: $Exports<'react-highcharts/dist/index'>;
}
declare module 'react-highcharts/dist/index.src.js' {
  declare module.exports: $Exports<'react-highcharts/dist/index.src'>;
}
declare module 'react-highcharts/dist/ReactHighcharts.js' {
  declare module.exports: $Exports<'react-highcharts/dist/ReactHighcharts'>;
}
declare module 'react-highcharts/dist/ReactHighcharts.src.js' {
  declare module.exports: $Exports<'react-highcharts/dist/ReactHighcharts.src'>;
}
declare module 'react-highcharts/dist/ReactHighmaps.js' {
  declare module.exports: $Exports<'react-highcharts/dist/ReactHighmaps'>;
}
declare module 'react-highcharts/dist/ReactHighmaps.src.js' {
  declare module.exports: $Exports<'react-highcharts/dist/ReactHighmaps.src'>;
}
declare module 'react-highcharts/dist/ReactHighstock.js' {
  declare module.exports: $Exports<'react-highcharts/dist/ReactHighstock'>;
}
declare module 'react-highcharts/dist/ReactHighstock.src.js' {
  declare module.exports: $Exports<'react-highcharts/dist/ReactHighstock.src'>;
}
declare module 'react-highcharts/dist/RedrawOnPrint.js' {
  declare module.exports: $Exports<'react-highcharts/dist/RedrawOnPrint'>;
}
declare module 'react-highcharts/dist/RedrawOnPrint.src.js' {
  declare module.exports: $Exports<'react-highcharts/dist/RedrawOnPrint.src'>;
}
declare module 'react-highcharts/nightwatch.js' {
  declare module.exports: $Exports<'react-highcharts/nightwatch'>;
}
declare module 'react-highcharts/src/bundle/ReactHighcharts.jsx' {
  declare module.exports: $Exports<'react-highcharts/src/bundle/ReactHighcharts'>;
}
declare module 'react-highcharts/src/bundle/ReactHighmaps.jsx' {
  declare module.exports: $Exports<'react-highcharts/src/bundle/ReactHighmaps'>;
}
declare module 'react-highcharts/src/bundle/ReactHighstock.jsx' {
  declare module.exports: $Exports<'react-highcharts/src/bundle/ReactHighstock'>;
}
declare module 'react-highcharts/src/chartsFactory.jsx' {
  declare module.exports: $Exports<'react-highcharts/src/chartsFactory'>;
}
declare module 'react-highcharts/src/fakeHighcharts.js' {
  declare module.exports: $Exports<'react-highcharts/src/fakeHighcharts'>;
}
declare module 'react-highcharts/src/Highmaps.jsx' {
  declare module.exports: $Exports<'react-highcharts/src/Highmaps'>;
}
declare module 'react-highcharts/src/Highstock.jsx' {
  declare module.exports: $Exports<'react-highcharts/src/Highstock'>;
}
declare module 'react-highcharts/src/More.jsx' {
  declare module.exports: $Exports<'react-highcharts/src/More'>;
}
declare module 'react-highcharts/src/ReactHighcharts.jsx' {
  declare module.exports: $Exports<'react-highcharts/src/ReactHighcharts'>;
}
declare module 'react-highcharts/src/RedrawOnPrint.jsx' {
  declare module.exports: $Exports<'react-highcharts/src/RedrawOnPrint'>;
}
declare module 'react-highcharts/webpack.config.js' {
  declare module.exports: $Exports<'react-highcharts/webpack.config'>;
}
