// flow-typed signature: f98f2c5ce4025e2a4d99531893a20bab
// flow-typed version: <<STUB>>/react-clock_v^1.0.5/flow_v0.34.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-clock'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-clock' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-clock/app' {
  declare module.exports: any;
}

declare module 'react-clock/gulpfile' {
  declare module.exports: any;
}

declare module 'react-clock/jsx/app' {
  declare module.exports: any;
}

declare module 'react-clock/jsx/clientApp' {
  declare module.exports: any;
}

declare module 'react-clock/jsx/clock' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-clock/app.js' {
  declare module.exports: $Exports<'react-clock/app'>;
}
declare module 'react-clock/gulpfile.js' {
  declare module.exports: $Exports<'react-clock/gulpfile'>;
}
declare module 'react-clock/index' {
  declare module.exports: $Exports<'react-clock'>;
}
declare module 'react-clock/index.js' {
  declare module.exports: $Exports<'react-clock'>;
}
declare module 'react-clock/jsx/app.jsx' {
  declare module.exports: $Exports<'react-clock/jsx/app'>;
}
declare module 'react-clock/jsx/clientApp.jsx' {
  declare module.exports: $Exports<'react-clock/jsx/clientApp'>;
}
declare module 'react-clock/jsx/clock.jsx' {
  declare module.exports: $Exports<'react-clock/jsx/clock'>;
}
